
services:
  sub_project1:
    container_name: subdir1_service
    build:
      context: ./subdir1
      dockerfile: Dockerfile
  
    

  sub_project2:
    container_name: subdir2_service
    build:
      context: ./subdir2
      dockerfile: Dockerfile


  sub_project3:
    container_name: subdir2_service
    build:
      context: ./subdir2
      dockerfile: Dockerfile
  
  nginx:
      container_name: app_nginx
      build: ./nginx
      ports:
          - "443:443"
          - "80:80"
      volumes:
        - .:/code
        - certbot:/etc/letsencrypt
        - certbot:/var/www/certbot  

volumes:
  static:
  certbot: